---
- name: Clone keylime
  git:
    repo: https://github.com/keylime/keylime
    dest: /root/keylime

- name: Run python setup tools to install Keylime
  command: python setup.py install
  args:
    chdir: /root/keylime

- name: Move /etc/keylime.conf into /etc
  command: mv /root/keylime/keylime.conf /etc/keylime.conf
